# Generated by Django 5.2.1 on 2025-06-25 20:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arenda',
            name='dt',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2025, 6, 25, 20, 24, 15, 895376)),
        ),
    ]
